@startuml
!include <C4/C4_Context>

title Контекстная диаграмма системы - текущий монолит

System(монолит, "Монолитное приложение 'Тёплый дом'", "Приложение для управления")
System(устройства, "Устройства", "Датчики температуры, служебные устройства")

Person(пользователь, "Пользователь", "Владелец дома, пользователь")
Person(специалист, "Специалист по подключению", "Подключает устройства к системе")

SystemDb(db, "PostgreSQL", "Хранилище данных")

Rel(пользователь, монолит, "Управляет отоплением и устройствами")
Rel(специалист, монолит, "Подключает устройства")
Rel(монолит, устройства, "Собирает данные, управляет устройствами")
Rel(монолит, db, "Хранит данные")
@enduml
